agent_codeql:
  model: deepseek/deepseek-chat
  iterations: 20
  temperature: 1.0
  tokens: 8000

agent_reviewer:
  model: deepseek/deepseek-chat
  iterations: 10
  temperature: 1.0
  tokens: 8000

agent_sanity:
  model: deepseek/deepseek-chat
  iterations: None
  temperature: 1.0
  tokens: 8000

use_mitre_cache: true
use_cve_database: true # set to false to disable CVE database usage
