agent_codeql:
  model: gemini/gemini-3-pro-preview
  iterations: 20
  temperature: 1.0
  tokens: 8000

agent_reviewer:
  model: gemini/gemini-2.5-pro
  iterations: 10
  temperature: 1.0
  tokens: 8000

agent_sanity:
  model: gemini/gemini-2.5-pro
  iterations: None
  temperature: 1.0
  tokens: 8000

use_mitre_cache: true
use_cve_database: false
