# More tokens and more iterations are required for Java results
agent_codeql:
  model: claude-sonnet-4-6
  iterations: 20
  temperature: 1.0
  tokens: 25000

agent_reviewer:
  model: claude-sonnet-4-6
  iterations: 20
  temperature: 1.0
  tokens: 25000

agent_sanity:
  model: claude-sonnet-4-6
  iterations: None
  temperature: 1.0
  tokens: 25000

use_mitre_cache: true
use_cve_database: false # already set to false in this config
