agent_codeql:
  model: deepseek/deepseek-reasoner
  iterations: 20
  temperature: 1.0
  tokens: 8000

agent_reviewer:
  model: deepseek/deepseek-reasoner
  iterations: 10
  temperature: 1.0
  tokens: 8000

agent_sanity:
  model: deepseek/deepseek-reasoner
  iterations: None
  temperature: 1.0
  tokens: 8000

use_mitre_cache: true
use_cve_database: false
