agent_codeql:
  model: claude-sonnet-4-5-20250929
  iterations: 20
  temperature: 1.0
  tokens: 8000

agent_reviewer:
  model: claude-haiku-4-5-20251001
  iterations: 10
  temperature: 1.0
  tokens: 8000

agent_sanity:
  model: claude-haiku-4-5-20251001
  iterations: None
  temperature: 1.0
  tokens: 8000

use_mitre_cache: true
use_cve_database: true # set to false to disable CVE database usage
