agent_codeql:
  model: gemini/gemini-3-pro-preview
  iterations: 20
  temperature: 0.0
  tokens: 8000 # max tokens needed are double to claude's

agent_reviewer:
  model: gemini/gemini-2.5-pro # flash model cannot handle this
  iterations: 10
  temperature: 0.0
  tokens: 8000 # max tokens needed are double to claude's

agent_sanity:
  model: gemini/gemini-2.5-pro # flash model can somewhat handle this
  iterations: None
  temperature: 0.0
  tokens: 8000 # max tokens needed are double to claude's

use_mitre_cache: true
use_cve_database: false
